### ISSUE TITLE
Friendly fire issue regarding the ultimate weapons and the royal guardian/big bertha

### ISSUE THREAD

**Issue by pantsguyapp** [ChaosAwakens/ChaosAwakens#111]
You can damage your pets with it, in original orespawn you can. The ultimate bow is supposed to heal your pets for 1hp if you accidentally hit a pet with its arrow.

**Comment by RaveTr** [comment]
Planning to have this fixed by next patch (0.12.0.1). Keeping this issue open until then.

**Comment by RaveTr** [comment]
Patched || Full patch coming in 0.12.1.0
