### ISSUE TITLE
Ultimate bow shakes the screen ever so slightly with each shot fired.

### ISSUE THREAD

**Issue by pantsguyapp** [ChaosAwakens/ChaosAwakens#112]
Title, its mildly annoying to have your screen be moved just a bit with each shots.

**Comment by RaveTr** [comment]
Fixed for next update (rewrite of the entire mod).

In the meantime, don't hold them around your pets.

**Comment by RaveTr** [comment]
I'll probably mark all these issues as closed once 0.12 is out, if not before.

**Comment by RaveTr** [comment]
Fixed in 0.12.
