### ISSUE TITLE
Strong mobs should have a pseudo health bar and gain passive healing

### ISSUE THREAD

**Issue by pantsguyapp** [ChaosAwakens/ChaosAwakens#113]
More pattern to og orespawn here, where strong, hard to beat mobs usually get a health bar if you're looking at them. Moreover, they also gain the ability to passively heal.
The healing thing is given to most, if not all of the mobs.

**Comment by RaveTr** [comment]
0.12 overhauled everything. Feel free to make this suggestion in more detail in our Discord server.
