### ISSUE TITLE
Ultimate bow is able to damage the parts of Ice and Fire dragons.

### ISSUE THREAD

**Issue by pantsguyapp** [ChaosAwakens/ChaosAwakens#115]
For some reasons, the bow only recognize the very center part as being tamed, so if the arrow hit a wing or head hitbox, the tamed dragon got damaged. This can be easily fixed with the friendly fire mod, but that mod can recognize the different hitboxes as tamed, so this mod should too.

Tested with singular hitbox mobs, and the bow heal them for 5 hp each, only the dragons are being troublesome ;-)

**Comment by RaveTr** [comment]
I believe multipart entities will only concern us in 0.13.x.x+, the port (in which we will be writing a number of systems from the ground up. No, no insane ETAs this time lol).

I'll have to revisit this once we reach that point. Leaving it open for now.

**Comment by RaveTr** [comment]
Closing this, may reopen it in the foreseeable future if necessary.
