### ISSUE TITLE
Mob having a really hard time hitting mobs against strafing opponents.

### ISSUE THREAD

**Issue by pantsguyapp** [ChaosAwakens/ChaosAwakens#116]
Not sure if this still in 0.12, but I have noticed that if a mob can strife, like a vanilla skeletons, then a few mobs from this mod will miss its attack due to it not being able to attack immediately because it needs to sync with the animation. 

Here's a demonstration video, sorry for the music but Idk how to make my own recording:
https://youtu.be/bCjN_3XU128?t=432

Tested myself as well, can confirm this happen for the herc beetle as the least.

**Comment by RaveTr** [comment]
0.12 entirely reworks AI and animations + literally everything else anyway, so uhh, fixed for next update.

(Will close all these issues when the update is out).

**Comment by pantsguyapp** [comment]
What about this one.
https://discord.com/channels/987382621560537108/987403325693636618/1130143293548810281
This is a preview od a mob for 0.12 I'd suppose. As we can see the pounder's attack missed a cow that was moving just a bit away from it. And I can see skeletons also move away or side way as they strife.

**Comment by pantsguyapp** [comment]
Please correct me if I am wrong.

**Comment by RaveTr** [comment]
They now have proper AI that dynamically interacts with one another (panicking, etc.) (yes, custom animations). Also accounted for cause, well, AI got overhauled.

I will not be disclosing anything else here for the time being. If it's an improvement suggestion, feel free to drop it in our Discord.

**Comment by RaveTr** [comment]
Fixed in 0.12.
