### ISSUE TITLE
Herc beetle cannot harm robot

### ISSUE THREAD

**Issue by pantsguyapp** [ChaosAwakens/ChaosAwakens#124]
Not sure if intentional but this is what I found in the new update.
https://youtu.be/GGlKaqcrsAs?si=GGFQbRfRisaQj5kZ

**Comment by FunkyMonk16** [comment]
It's not, thanks for this, will try and fix asap.

**Comment by RaveTr** [comment]
I couldn't replicate this. What mods did you have installed?

**Comment by RaveTr** [comment]
Patched in 0.12.0.1
