### ISSUE TITLE
Robo warrior doesnt drop its loo table

### ISSUE THREAD

**Issue by pantsguyapp** [ChaosAwakens/ChaosAwakens#125]
When you killed it, it drops nothing.

**Comment by FunkyMonk16** [comment]
Noted. Was testing this and it was working fine before. Will check again later.

**Comment by RaveTr** [comment]
This can happen due to MSPT lag spikes (even if they're pretty unnoticeable).

Will have this fixed for 0.12.0 1. Leaving this open until then.

**Comment by RaveTr** [comment]
Patched in 0.12.0.1
