### ISSUE TITLE
Raygun balancing and stuff

### ISSUE THREAD

**Issue by pantsguyapp** [ChaosAwakens/ChaosAwakens#135]
This has been a long running issue but I will still post it here since it hasnt got resolved in so long.

The raygun (and the lightning staff) has some issues that need to be fixed, such as:
- The firing sound uses the bow sound.
- No attack cooldown, you can spam click it to your hearts content, same for lightning staff.
- No knockback as you fire it.
- Infinite durability (?)

**Comment by RaveTr** [comment]
The raygun is nowhere near done and will be overhauled in a future content update.

**Comment by pantsguyapp** [comment]
But what about the thunder staff?

**Comment by RaveTr** [comment]
None of the content currently in CA is complete and it'll likely stay that way for a while, so I'm just letting you know that we are aware lol. Feel free to make feature/mechanic suggestions in the Discord :)

**Comment by pantsguyapp** [comment]
I have disabled my Discord account so can I just post mine here, can you guys add in a chest?

**Comment by RaveTr** [comment]
As much as we appreciate input, the Github Issue Tracker should be for mod-related issues/questioning whether a mechanic or set of mechanics is/are issue(s), not feature suggestions.

But as you were told in the Discord server before disabling your account, there will likely be some form of chest(s) added to CA later on.

If you have any other suggestions, you're welcome to reactivate your Discord account or make a new one (just don't join with multiple alts lol).

**Comment by pantsguyapp** [comment]
Oh, i must have missed out on that information, since I immediately disabled my acc after putting up the suggestion. Still, it is fascinating to know such a thing, hopefully the robot crate can be turned into a chest also.
